#!/bin/bash

export VER=1.0.5
export ANDROID_HOME=/home/dz/prg/android-sdk-linux_x86


mvn -Dmaven.test.skip=true compile android:dex android:apk jarsigner:sign 


mv target/irish-tides-$VER.apk target/irish-tides-$VER-.apk
$ANDROID_HOME/build-tools/20.0.0/zipalign -f -v 4 target/irish-tides-$VER-.apk target/irish-tides-$VER.apk 